language: node_js
sudo: false
node_js:
  - "lts/*"
  - "stable"
cache: yarn
install:
  - yarn install
  - yarn global add codecov
script:
  - yarn run ci
after_success:
  - codecov
notifications:
  email:
    on_success: change
    on_failure: always
